import pandas as pd

# Read in the Defenders Excel scrapped file
dataset = pd.read_excel('fpl_forward.xlsx')

# Fill in any cells that might be blank or NaN
dataset.fillna(0, inplace=True)

# If the player is in the MidPrice
dataset['Predict'] = (((dataset['%%xGI'])*-1.767) + ((dataset['Shots'])*-5.818) + ((dataset['On Target'])*0.671) + ((dataset['Shots in Box'])*5.859) + ((dataset['Shots Outside Box'])*6.209) + ((dataset['NPxG'])*-6.442) + ((dataset['Goals'])*10.082) + ((dataset['Goals from Outside Box'])*-3.819) + ((dataset['Headed Goals'])*-1.041) + ((dataset['Final 3rd Passes'])*0.074) + ((dataset['Total Crosses'])*0.414) + ((dataset['%% Successful Crosses'])*0.004) + ((dataset['Assists'])*4.447) + ((dataset['xAtt'])*-1.370) + ((dataset['Expected Points'])*1.991) + ((dataset['BPS'])*-0.224) + ((dataset['Bonus Points'])*0.839) + ((dataset['Points'])*-0.985) + ((dataset['Goals Conceded'])*-0.371) + ((dataset['Recovery'])*-0.128) + ((dataset['Shots Conceded OT'])*-0.525) + ((dataset['SP'])*0.216) + ((dataset['Headed Shots Conceded'])*-0.198) + ((dataset['BC Conceded'])*-1.023) + ((dataset['xGC'])*2.951) + ((dataset['Total Passes'])*-0.417) + ((dataset['Successful Passes'])*0.634) + ((dataset['%% Successful Passes'])*-0.069) + ((dataset['Opposition Half Passes'])*0.471) + ((dataset['Successful Opposition Half Passes'])*-0.689) + ((dataset['%% Successful Opposition Half Passes'])*0.068) + ((dataset['Total Touches'])*-0.060) + ((dataset['Entries into Final 3rd'])*0.209) + ((dataset['Fouled in Final 3rd'])*0.377) + ((dataset['Total Penalties'])*-7.563) + ((dataset['Penalty Goals'])*3.312) + (3.494))

# If the player is a Premium
dataset.loc[dataset['Price'] >= 10, 'Predict'] = (((dataset['%%xGI'])*4.137) + ((dataset['%%GI'])*-3.863) + ((dataset['NPxG'])*27.86) + ((dataset['Goals'])*4.39) + ((dataset['Headed Goals'])*2.838) + ((dataset['Total Crosses'])*2.201) + ((dataset['Successful Crosses'])*-5.843) + ((dataset['Key Passes'])*-11.692) + ((dataset['Expected Assists'])*26.815) + ((dataset['Yellow Card'])*2.719) + ((dataset['Creativity'])*0.998) + ((dataset['xAtt'])*-7.630) + ((dataset['bBPS'])*0.483) + ((dataset['BPS'])*-0.53) + ((dataset['Points'])*1.855) + ((dataset['Tackles Won'])*-1.365) + ((dataset['Recovery'])*0.522) + ((dataset['Clearances'])*-0.964) + ((dataset['Blocks'])*-1.923) + ((dataset['Interceptions'])*1.555) + ((dataset['Shots Conceded'])*-0.606) + ((dataset['Shots Conceded In Box'])*0.473) + ((dataset['Shots Conceded OT'])*-0.512) + ((dataset['SP'])*1.064) + ((dataset['Headed Shots Conceded'])*-0.876) + ((dataset['xGC'])*2.425) + ((dataset['Total Passes'])*2.494) + ((dataset['Successful Passes'])*-3.237) + ((dataset['%% Successful Passes'])*0.44) + ((dataset['Opposition Half Passes'])*-2.446) + ((dataset['Successful Opposition Half Passes'])*2.827) + ((dataset['%% Successful Opposition Half Passes'])*-0.297) + ((dataset['Accurate Throughballs'])*-7.351) + ((dataset['Entries into Final 3rd'])*0.678) + ((dataset['Fouled in Final 3rd'])*-1.493) + ((dataset['Total Penalties'])*32.103) + ((dataset['Penalty Goals'])*-7.216) - (5.522))

# If the player is a Budget Player
dataset.loc[dataset['Price'] < 6.5, 'Predict'] = (((dataset['Minutes'])*0.009) + ((dataset['On Target'])*0.305) + ((dataset['Shots in Box'])*-0.299) + ((dataset['Big Chances'])*1.790) + ((dataset['Headed Goals'])*-0.941) + ((dataset['%% Successful Crosses'])*-0.009) + ((dataset['Total Indirect FK'])*-0.715) + ((dataset['Key Passes'])*-0.617) + ((dataset['Expected Assists'])*3.922) + ((dataset['Cleansheet'])*0.918) + ((dataset['Expected Points'])*-0.630) + ((dataset['bBPS'])*0.110) + ((dataset['Bonus Points'])*-0.789) + ((dataset['Total Tackles'])*-0.632) + ((dataset['Tackles Won'])*0.794) + ((dataset['Blocks'])*-0.602) + ((dataset['Interceptions'])*-0.682) + ((dataset['Shots Conceded'])*0.098) + ((dataset['Shots Conceded OT'])*-0.2) + ((dataset['Headed Shots Conceded'])*-0.116) + ((dataset['BC Conceded'])*0.155) + ((dataset['Total Passes'])*0.088) + ((dataset['Opposition Half Passes'])*-0.176) + ((dataset['Total Throughballs'])*0.729) + ((dataset['Accurate Throughballs'])*-1.549) + ((dataset['Touches in Box'])*0.288) + ((dataset['Entries into Final 3rd'])*0.3) + ((dataset['Entries into Box'])*0.324) + (3.811))

# Export to an Excel file & A General file of only predicitions
selectList = ['Name', 'Team Name', 'Price', 'Predict']
dataToWrite = dataset[selectList]
dataToWrite.to_excel('fpl_forwardNew.xlsx', index=False)