import pandas as pd

# Read in the Midfielders Excel scrapped file
dataset = pd.read_excel('fpl_midfielders.xlsx')

# Fill in any cells that might be blank or NaN
dataset.fillna(0, inplace=True)

# If the player is in the MidPrice
dataset['Predict'] = (((dataset['Minutes'])*-0.066) + ((dataset['%%xGI'])*8.512) + ((dataset['%%GI'])*-4.499) + ((dataset['xGI'])*3.871) + ((dataset['Shots'])*13.821) + ((dataset['Shots in Box'])*-13.306) + ((dataset['Shots Outside Box'])*-14.405) + ((dataset['NPxG'])*81.178) + ((dataset['Expected Goals'])*-92.455) + ((dataset['Goals'])*22.976) + ((dataset['Goals from Outside Box'])*3.539) + ((dataset['Final 3rd Passes'])*1.742) + ((dataset['Final 3rd Successesful Passes'])*-1.997) + ((dataset['Total Crosses'])*1.829) + ((dataset['Successful Crosses'])*-4.354) + ((dataset['Total Corners'])*1.268) + ((dataset['Total Indirect FK'])*-3.73) + ((dataset['Key Passes'])*4.192) + ((dataset['Expected Assists'])*-17.905) + ((dataset['Assists'])*14.519) + ((dataset['Red Card'])*-10.806) + ((dataset['Cleansheet'])*-1.834) + ((dataset['Creativity'])*-0.201) + ((dataset['Influence'])*-0.436) + ((dataset['xAtt'])*-2.217) + ((dataset['Expected Points'])*4.041) + ((dataset['Bonus Points'])*-2.106) + ((dataset['Points'])*-1.415) + ((dataset['Total Tackles'])*-1.145) + ((dataset['Tackles Won'])*2.395) + ((dataset['%% Accurate Tackles'])*-0.017) + ((dataset['Blocks'])*8.989) + ((dataset['Interceptions'])*0.824) + ((dataset['Shots Conceded'])*0.33) + ((dataset['Shots Conceded In Box'])*-1.251) + ((dataset['Shots Conceded OT'])*0.887) + ((dataset['Headed Shots Conceded'])*0.59) + ((dataset['BC Conceded'])*0.447) + ((dataset['Successful Passes'])*0.147) + ((dataset['%% Successful Passes'])*-0.172) + ((dataset['Opposition Half Passes'])*-1.55) + ((dataset['Successful Opposition Half Passes'])*1.634) + ((dataset['Total Throughballs'])*-2.712) + ((dataset['Touches in Box'])*0.54) + ((dataset['Entries into Final 3rd'])*0.395) + ((dataset['Fouled in Final 3rd'])*-0.936) + ((dataset['Accurate Indirect FK'])*7.762) + ((dataset['Total Direct FK'])*2.026) + ((dataset['Total Penalties'])*67.859) + ((dataset['Penalty Goals'])*-14.846) + (13.693))

# If the player is a Premium
dataset.loc[dataset['Price'] >= 10, 'Predict'] = (((dataset['%%xGI'])*-14.789) + ((dataset['%%GI'])*10.634) + ((dataset['xGI'])*-6.71) + ((dataset['Goal Involvement'])*-0.123) + ((dataset['Shots'])*-2.292) + ((dataset['Big Chances'])*-8.566) + ((dataset['Headed Shots'])*-9.577) + ((dataset['Goals In Box'])*20.146) + ((dataset['Headed Goals'])*22.801) + ((dataset['Final 3rd Passes'])*-0.565) + ((dataset['Total Crosses'])*2.815) + ((dataset['Successful Crosses'])*-11.228) + ((dataset['%% Successful Crosses'])*0.07) + ((dataset['Total Indirect FK'])*-7.031) + ((dataset['Key Passes'])*-26.138) + ((dataset['Big Chances Created'])*3.794) + ((dataset['Red Card'])*41.845) + ((dataset['Cleansheet'])*8.845) + ((dataset['Creativity'])*3.02) + ((dataset['Influence'])*-0.622) + ((dataset['Expected Points'])*4.461) + ((dataset['bBPS'])*-0.882) + ((dataset['Bonus Points'])*-6.764) + ((dataset['Goals Conceded'])*5.416) + ((dataset['Clearances'])*4.610) + ((dataset['Shots Conceded'])*3.728) + ((dataset['Shots Conceded In Box'])*-2.504) + ((dataset['BC Conceded'])*12.063) + ((dataset['xGC'])*-29.774) + ((dataset['Accurate Throughballs'])*-11.902) + ((dataset['Total Touches'])*-0.329) + ((dataset['Touches in Box'])*-0.437) + ((dataset['Entries into Final 3rd'])*1.043) + ((dataset['Fouled in Final 3rd'])*3.774) + ((dataset['Fouled in Box'])*-9.337) + ((dataset['Corners into Box'])*-2.828) + ((dataset['Total Penalties'])*-23.952) + ((dataset['Penalty Goals'])*23.333) + (5.825))

# If the player is a Budget Player
dataset.loc[dataset['Price'] < 6.5, 'Predict'] = (((dataset['Minutes'])*-0.031) + ((dataset['%%xGI'])*4.062) + ((dataset['%%GI'])*-1.143) + ((dataset['Goal Involvement'])*-0.033) + ((dataset['Shots'])*-0.554) + ((dataset['On Target'])*-2.825) + ((dataset['Shots Outside Box'])*0.478) + ((dataset['Big Chances'])*-5.386) + ((dataset['Headed Shots'])*1.352) + ((dataset['Expected Goals'])*10.442) + ((dataset['Goals'])*-2.818) + ((dataset['Goals In Box'])*2.397) + ((dataset['Headed Goals'])*-5.683) + ((dataset['Final 3rd Passes'])*0.040) + ((dataset['%% Final 3rd Successful'])*0.015) + ((dataset['Successful Crosses'])*0.795) + ((dataset['%% Successful Crosses'])*-0.005) + ((dataset['Key Passes'])*-0.13) + ((dataset['Expected Assists'])*-6.471) + ((dataset['Assists'])*-0.906) + ((dataset['Influence'])*-0.059) + ((dataset['xAtt'])*1.4) + ((dataset['BPS'])*0.091) + ((dataset['Bonus Points'])*-0.488) + ((dataset['Points'])*0.517) + ((dataset['Goals Conceded'])*0.2) + ((dataset['Total Tackles'])*0.342) + ((dataset['Tackles Won'])*-0.650) + ((dataset['%% Accurate Tackles'])*0.006) + ((dataset['Recovery'])*0.047) + ((dataset['Blocks'])*0.380) + ((dataset['Shots Conceded'])*-0.059) + ((dataset['Shots Conceded OT'])*-0.098) + ((dataset['Headed Shots Conceded'])*0.298) + ((dataset['Total Passes'])*0.29) + ((dataset['Successful Passes'])*-0.293) + ((dataset['%% Successful Passes'])*0.075) + ((dataset['Opposition Half Passes'])*-0.209) + ((dataset['Successful Opposition Half Passes'])*0.181) + ((dataset['%% Successful Opposition Half Passes'])*-0.054) + ((dataset['Total Throughballs'])*0.405) + ((dataset['Touches in Box'])*0.181) + ((dataset['Entries into Final 3rd'])*-0.040) + ((dataset['Fouled in Final 3rd'])*0.374) + ((dataset['Fouled in Box'])*-4.470) + ((dataset['Accurate Indirect FK'])*-0.780) + ((dataset['Total Direct FK'])*0.796) + ((dataset['Goals Direct FK'])*2.505) + ((dataset['Penalty Goals'])*-5.484) - (0.110))

# Export to an Excel file & A General file of only predicitions
selectList = ['Name', 'Team Name', 'Price', 'Predict']
dataToWrite = dataset[selectList]
dataToWrite.to_excel('fpl_midfieldersNew.xlsx', index=False)